# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transcribe_pb2 as transcribe__pb2


class TranscriberStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Trans = channel.unary_unary(
                '/transcribe.Transcriber/Trans',
                request_serializer=transcribe__pb2.AudioData.SerializeToString,
                response_deserializer=transcribe__pb2.Text.FromString,
                )


class TranscriberServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Trans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriberServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Trans': grpc.unary_unary_rpc_method_handler(
                    servicer.Trans,
                    request_deserializer=transcribe__pb2.AudioData.FromString,
                    response_serializer=transcribe__pb2.Text.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transcribe.Transcriber', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transcriber(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Trans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transcribe.Transcriber/Trans',
            transcribe__pb2.AudioData.SerializeToString,
            transcribe__pb2.Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
